version: '3.8'

services:
  db:
    image: mysql:8.3
    restart: always
    container_name: skillsync-db
    environment:
      MYSQL_DATABASE: skillsync_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: skillsync_user
      MYSQL_PASSWORD: skillsync_password
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skillsync-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/skillsync_db
      SPRING_DATASOURCE_USERNAME: skillsync_user
      SPRING_DATASOURCE_PASSWORD: skillsync_password
    depends_on:
      - db

volumes:
  db_data: